services:
  weather-app:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - app-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/cities"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  app-data:
    driver: local

networks:
  default:
    name: weather-network